version: "3.8"
services:
  db:
    build: 
      context: .
      dockerfile: DevSkill.Inventory.Db/Dockerfile
    image: "safinsarker/createi_mage_with_github_actions:database"  
    env_file: 
      - DevSkill.Inventory.Db/db.env
    expose: 
      - "1432"
    ports: 
      - "1432:1433"
    restart: always
    networks:
      - devskillinventory_network

  web:
    build: 
      context: .
      dockerfile: DevSkill.Inventory.Web/Dockerfile
    image: "safinsarker/createi_mage_with_github_actions:web"  
    env_file: 
      - DevSkill.Inventory.Web/web.env
    ports:
      - "8004:80"
    depends_on:
      - db
    networks:
      - devskillinventory_network
    restart: always

networks:
  devskillinventory_network:
    driver: bridge
