name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build project
      run: dotnet build --configuration Release

    # Run unit tests only if there are test projects
    - name: Run unit tests
      run: |
        if [ -f "DevSkill.Inventory.Application.Tests/DevSkill.Inventory.Application.Tests.csproj" ]; then
          dotnet test --configuration Release --no-build
        else
          echo "No tests found, skipping test step"
        fi
