name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'
    
    - name: Restore dependencies
      run: dotnet restore ./DevSkill.Inventory/DevSkill.Inventory.Web/DevSkill.Inventory.Web.csproj
    
    - name: Clean previous builds
      run: dotnet clean ./DevSkill.Inventory/DevSkill.Inventory.Application.Tests/DevSkill.Inventory.Application.Tests.csproj --configuration Release

    - name: Build project
      run: dotnet build ./DevSkill.Inventory/DevSkill.Inventory.Web/DevSkill.Inventory.Web.csproj --configuration Release

    - name: Run unit tests
      run: dotnet test ./DevSkill.Inventory/DevSkill.Inventory.Application.Tests/DevSkill.Inventory.Application.Tests.csproj --configuration Release

    # Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verify installation

    # Build the database service Docker image
    - name: Build database Docker image
      run: |
        docker-compose -f DevSkill.Inventory/docker-compose.yml build db
        docker tag safinsarker/createi_mage_with_github_actions:tagname safinsarker/createi_mage_with_github_actions:database

    # Build the web service Docker image
    - name: Build web Docker image
      run: |
        docker-compose -f DevSkill.Inventory/docker-compose.yml build web
        docker tag safinsarker/createi_mage_with_github_actions:tagname safinsarker/createi_mage_with_github_actions:web

    # Push database image to DockerHub
    - name: Push database Docker image to DockerHub
      run: |
        docker push safinsarker/createi_mage_with_github_actions:database

    # Push web image to DockerHub
    - name: Push web Docker image to DockerHub
      run: |
        docker push safinsarker/createi_mage_with_github_actions:web
