name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the database service Docker image
    - name: Build database Docker image
      run: |
        docker-compose -f DevSkill.Inventory/docker-compose.yml build db
        docker tag safinsarker/createi_mage_with_github_actions:tagname safinsarker/createi_mage_with_github_actions:database

    # Build the web service Docker image
    - name: Build web Docker image
      run: |
        docker-compose -f DevSkill.Inventory/docker-compose.yml build web
        docker tag safinsarker/createi_mage_with_github_actions:tagname safinsarker/createi_mage_with_github_actions:web

    # Push database image to DockerHub
    - name: Push database Docker image to DockerHub
      run: |
        docker push safinsarker/createi_mage_with_github_actions:database

    # Push web image to DockerHub
    - name: Push web Docker image to DockerHub
      run: |
        docker push safinsarker/createi_mage_with_github_actions:web
