name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'
    
    - name: Restore dependencies
      run: dotnet restore ./DevSkill.Inventory/DevSkill.Inventory.Web/DevSkill.Inventory.Web.csproj
    
    - name: Clean previous builds
      run: dotnet clean ./DevSkill.Inventory/DevSkill.Inventory.Application.Tests/DevSkill.Inventory.Application.Tests.csproj --configuration Release

    - name: Build project
      run: dotnet build ./DevSkill.Inventory/DevSkill.Inventory.Web/DevSkill.Inventory.Web.csproj --configuration Release

    - name: Run unit tests
      run: dotnet test ./DevSkill.Inventory/DevSkill.Inventory.Application.Tests/DevSkill.Inventory.Application.Tests.csproj --configuration Release
